---
title: "cleanGST"
author: "Caitlin Page"
date: "2026-02-05"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

```{r}
library(plyranges)
library(dplyr)
library(ggplot2)

library(BiasedUrn)
library(ggVennDiagram)
library(org.Hs.eg.db)
```



```{r}
wgbs_counts <- readRDS("../output/wgbs_counts.rds")
biomart_genes <- readRDS("../output/genes_biomart.rds")
dmrcate_seq_dmr <- readRDS("../output/dmrcate_seq_dmr.rds") %>% data.frame()
dmrcate_seq_anno <- readRDS("../output/dmrcate_seq_anno.rds")
dmrcate_seq_anno <- data.frame(dmrcate_seq_anno@ranges)

immuneGO <- read.table("../data/gene_sets/GO-immune-system-process.txt", header = FALSE)
names(immuneGO) <- "GOID"
immuneGO <- distinct(immuneGO)
```

##########
```{r}
genes_with_pos3 <- pair_overlaps(biomart_genes %>%
  mutate(start = TSS - 10000,
         end = TSS + 10000) %>% .[,c(1:8)] %>% as_granges(), as_granges(wgbs_counts[,1:4])) %>% data.frame()

genes_with_pos3 %>% mutate(cpg_pos = granges.y.start, 
                          dist_from_tss = ifelse(granges.x.strand == "+", cpg_pos - TSS, TSS - cpg_pos)) %>% 
  filter(abs(dist_from_tss) <= 2000) %>%
  ggplot(aes(x = dist_from_tss)) +
  geom_bar()
```
```{r}
pair_overlaps(txdb_genes %>%
  mutate(TSS = ifelse(strand == "+", start, end),
         actual_start = start,
         actual_end = end,
         start = TSS - 10000,
         end = TSS + 10000,
         actual_width = width) %>% .[,c(1:4,6:11)] %>% as_granges(), as_granges(wgbs_counts[,1:4])) %>% data.frame() %>% 
  mutate(cpg_pos = granges.y.start, 
                          dist_from_tss = ifelse(granges.x.strand == "+", cpg_pos - TSS, TSS - cpg_pos),
         up_down = ifelse(dist_from_tss >= 0, "downstream", "upstream")) %>%
  group_by(gene_id, up_down) %>%
  summarise(n_cg = n(), density = n()/10000 * 100) %>%
  ggplot(aes(x = n_cg, colour = up_down)) +
  geom_density()
```

```{r}
txdb_genes_mod <- find_overlaps(txdb_genes %>%
  mutate(TSS = ifelse(strand == "+", start, end),
         start = TSS - 2000,
         end = TSS + 2000) %>% .[,c(1:4,6)] %>% as_granges(), 
  as_granges(wgbs_counts[,1:4])) %>% data.frame() %>%
  group_by(gene_id, seqnames, start, end, strand, width) %>%
  summarise(num_cg = n()) %>% ungroup() %>% data.frame()
gene_try <- find_overlaps(as_granges(mutate(dmrcate_seq_dmr, id = 1:nrow(dmrcate_seq_dmr))), as_granges(txdb_genes_mod)) %>% data.frame()
gene_info <- txdb_genes_mod %>% mutate(is_de = ifelse(gene_id %in% gene_try$gene_id, 1, 0)) %>% distinct(gene_id, num_cg, is_de, width)

txdb_genes_mod_og <- find_overlaps(txdb_genes %>% as_granges(), 
  as_granges(wgbs_counts[,1:4])) %>% data.frame() %>%
  group_by(gene_id, seqnames, start, end, strand, width) %>%
  summarise(num_cg = n()) %>% ungroup() %>% data.frame()
gene_try_og <- find_overlaps(as_granges(mutate(dmrcate_seq_dmr, id = 1:nrow(dmrcate_seq_dmr))), as_granges(txdb_genes_mod_og)) %>% data.frame()
gene_info_og <- txdb_genes_mod_og %>% mutate(is_de = ifelse(gene_id %in% gene_try_og$gene_id, 1, 0)) %>% distinct(gene_id, num_cg, is_de, width)

gene_try_og_1k <- find_overlaps(as_granges(mutate(dmrcate_seq_dmr, id = 1:nrow(dmrcate_seq_dmr))[1:1000,]), as_granges(txdb_genes_mod_og)) %>% data.frame()
gene_info_og_1k <- txdb_genes_mod_og %>% mutate(is_de = ifelse(gene_id %in% gene_try_og_1k$gene_id, 1, 0)) %>% distinct(gene_id, num_cg, is_de, width)
```
```{r}
gene_info
upset_input <- list(Gene_tss2k = gene_info %>% filter(is_de == 1) %>% .$gene_id,
                    gene_whole = gene_info_og %>% filter(is_de == 1) %>% .$gene_id)
upset(fromList(upset_input), order.by = "freq", text.scale = 2)
```


```{r}
upset_input <- list(Gene_tss2k = gene_info %>% filter(is_de == 1) %>% .$gene_id,
                    gene_whole = gene_info_og %>% filter(is_de == 1) %>% .$gene_id,
                    gene_whole_1k = gene_info_og_1k %>% filter(is_de == 1) %>% .$gene_id)
upset(fromList(upset_input), order.by = "freq", text.scale = 2)
```

```{r}
run_test <- list(
  sig.eg = gene_info %>% filter(is_de == 1) %>% .$gene_id,
  universe = gene_info$gene_id,
  freq = gene_info$num_cg,
  de = gene_info$is_de,
  equiv = gene_info$num_cg
)
```

```{r}
gst_2ud <- run_miss_methyl_b(run_test, method = "Wallenius")
#gst_2ud_fisher <- run_miss_methyl_b(run_test, method = "Fishers")
gst_2ud_hyper <- run_miss_methyl_b(run_test, method = "None")
```

```{r}
run_test <- list(
  sig.eg = gene_info %>% filter(is_de == 1) %>% .$gene_id,
  universe = gene_info$gene_id,
  freq = gene_info$width,
  de = gene_info$is_de,
  equiv = gene_info$width
)
```

```{r}
gst_2ud_width <- run_miss_methyl_b(run_test, method = "Wallenius")
#gst_2ud_width_fisher <- run_miss_methyl_b(run_test, method = "Fishers")
gst_2ud_width_hyper <- run_miss_methyl_b(run_test, method = "None")
```

```{r}
gst_2ud <- gst_2ud[[1]]
gst_2ud_hyper <- gst_2ud_hyper[[1]]
gst_2ud$rank_fdr <- 1:nrow(gst_2ud)
gst_2ud_hyper$rank_fdr <- 1:nrow(gst_2ud_hyper)

gst_2ud_width <- gst_2ud_width[[1]]
gst_2ud_width_hyper <- gst_2ud_width_hyper[[1]]
gst_2ud_width$rank_fdr <- 1:nrow(gst_2ud_width)
gst_2ud_width_hyper$rank_fdr <- 1:nrow(gst_2ud_width_hyper)
```
```{r}
gst_15u5d <- gst_15u5d[[1]]
gst_15u5d_hyper <- gst_15u5d_hyper[[1]]
gst_15u5d$rank_fdr <- 1:nrow(gst_15u5d)
gst_15u5d_hyper$rank_fdr <- 1:nrow(gst_15u5d_hyper)

gst_15u5d_width <- gst_15u5d_width[[1]]
gst_15u5d_width_hyper <- gst_15u5d_width_hyper[[1]]
gst_15u5d_width$rank_fdr <- 1:nrow(gst_15u5d_width)
gst_15u5d_width_hyper$rank_fdr <- 1:nrow(gst_15u5d_width_hyper)
```


```{r}
upset_input <- list(TSS2k_GOMethSeq = gst_2ud %>% filter(FDR < 0.05) %>% .$GOID,
                    TSS2k_Biased = gst_2ud_hyper %>% filter(FDR < 0.05) %>% .$GOID)
upset(fromList(upset_input), order.by = "freq", text.scale = 2)
```

```{r}
truth_gst_100 <- rbind(
  gst_2ud[1:100,] %>% mutate(in_imm = cumsum(GOID %in% immuneGO$GOID), method = "TSS2k_GOMethSeq") %>% .[names(.) %in% c("rank_fdr", "in_imm", "method")],
  gst_2ud_hyper[1:100,] %>% mutate(in_imm = cumsum(GOID %in% immuneGO$GOID), method = "TSS2k_Biased") %>% .[names(.) %in% c("rank_fdr", "in_imm", "method")])

truth_gst_100 %>%
  ggplot(aes(x = rank_fdr, y = in_imm, colour = method)) +
  geom_line() +
  labs(x = "Rank", y = "Cumulative no. in immune sets") +
  theme_bw()
```

```{r}
truth_gst_100 <- rbind(
  gst_2ud[1:100,] %>% mutate(in_imm = cumsum(GOID %in% immuneGO$GOID), method = "TSS2k_GOMethSeq") %>% .[names(.) %in% c("rank_fdr", "in_imm", "method")],
  gst_2ud_hyper[1:100,] %>% mutate(in_imm = cumsum(GOID %in% immuneGO$GOID), method = "TSS2k_Biased") %>% .[names(.) %in% c("rank_fdr", "in_imm", "method")],
  gst[1:100,] %>% mutate(in_imm = cumsum(GOID %in% immuneGO$GOID), method = "GOMethSeq") %>% .[names(.) %in% c("rank_fdr", "in_imm", "method")],
  gst_hyper[1:100,] %>% mutate(in_imm = cumsum(GOID %in% immuneGO$GOID), method = "Biased") %>% .[names(.) %in% c("rank_fdr", "in_imm", "method")])

truth_gst_100 %>%
  ggplot(aes(x = rank_fdr, y = in_imm, colour = method)) +
  geom_line() +
  labs(x = "Rank", y = "Cumulative no. in immune sets") +
  theme_bw()
```

